server:
  port: 80

spring:
  application:
    name: outclass

####################################
# 데이터베이스 설정
####################################
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://panda5939.cafe24.com:3306/panda5939
    username: panda5939
    password: leeye-8979

  ####################################
  # JPA 설정
  ####################################
  jpa:
    open-in-view: true      #
    hibernate:
      ddl-auto: update      # create, update, ...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # 카멜표기를 스네이크 표기로 변환
    show-sql: true          # SQL 구문 보이기
    properties:
      hibernate:
        format_sql: true    # 포멧 처리해서 보이기
    #database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8 버전 사용