server:
  port: 80

spring:
  application:
    name: outclass


  ####################################
  # 자동갱신...
  ####################################
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: false

####################################
# 데이터베이스 설정
####################################


  ####################################
  # JPA 설정
  ####################################
  jpa:
    open-in-view: true      #
    hibernate:
      ddl-auto: update      # create, update, ...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # 카멜표기를 스네이크 표기로 변환
    show-sql: true          # SQL 구문 보이기
    properties:
      hibernate:
        format_sql: true    # 포멧 처리해서 보이기
    #database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8 버전 사용

  security:
    user:
      name: admin@naver.com
      password: 123456

  ####################################
  # 로그 정보 설정
  ####################################
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace  # 물음표에 바인드 파라미터 출력

####################################
# 파일저장정보
####################################
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

userImgLocation: D:/BigData/Tim_Project/outclass/src/main/resources/static/images
uploadPath: file:///D:/BigData/Tim_Project/outclass/src/main/resources/static/



